package interfaceModule.test;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import interfaceModule.java.ButtonMax;
import interfaceModule.java.ButtonMin;

import javax.swing.JFrame;

import java.awt.event.ActionEvent;

import javax.swing.JLabel;
/**
 *
 * @author jakal
 */
public class MainUITest extends JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static MainUITest instance = null;
    
    /**
     * Creates new form MainUI
     */
    private MainUITest() {
        initComponents();
    }
    
    public static MainUITest getInstance(){
    if (instance == null) instance = new MainUITest();
        return instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        max = new ButtonMax(20, 20, 120, 30);
    	add(max);
    	min = new ButtonMin(20, 60, 120, 30);
    	add(min);
    	
    	result = new JLabel("result");
    	result.setSize(60, 25);
    	result.setLocation(40, 150);
    	add(result);
    	
        //javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(null);
        /*
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup())
        );
        */

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getQuery(){
    }
    
    public void searchBtn_OnClickEvent(ActionEvent e){
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainUITest main = new MainUITest();
                main.setSize(320,240);
                main.setResizable(false);
                main.setLocationRelativeTo(null);
                main.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonMax max;
    private ButtonMin min;
    static JLabel result;
    // End of variables declaration//GEN-END:variables
}
