/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceModule.java;

import databaseModule.java.ConnectionDb;
import databaseModule.java.MySQLConnectionDB;

import java.math.BigInteger;
import java.sql.SQLException;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import com.mysql.jdbc.StringUtils;

import queriesModule.java.*;
import utilitiesModule.java.Paillier;

/**
 *
 * @author -Oana-
 */
public class MainUI extends javax.swing.JFrame {

	/**
	 * Creates new form INTERFACE
	 */
	public MainUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField5 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldQ = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldUserName = new javax.swing.JTextField();
		jTextFieldP = new javax.swing.JTextField();
		jButtonCreate = new javax.swing.JButton();
		jButtonValidate = new javax.swing.JButton();
		jButtonSum = new javax.swing.JButton();
		jTextFieldSum = new javax.swing.JTextField();
		jComboBoxUserLevel = new javax.swing.JComboBox();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel6 = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		jTextFieldName = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextFieldAge = new javax.swing.JTextField();
		jTextFieldCost = new javax.swing.JTextField();
		jButtonInsert = new javax.swing.JButton();
		jButtonGenerateData = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setAlwaysOnTop(false);

		jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
		jLabel1.setText("Private Statistics");

		jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
		jLabel2.setText("Username");

		jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
		jLabel3.setText("p");

		jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
		jLabel4.setText("q");

		jTextFieldUserName
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jTextField2ActionPerformed(evt);
					}
				});

		jButtonCreate.setText("Create");
		jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCreateActionPerformed(evt);
			}
		});

		jButtonValidate.setText("Validate");
		jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonValidateActionPerformed(evt);
			}
		});

		jButtonSum.setText("SUM");
		jButtonSum.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSumActionPerformed(evt);
			}
		});

		jComboBoxUserLevel.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "SYSTEM", "USERLEVEL1", "USERLEVEL2" }));
		jComboBoxUserLevel
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jComboBox1ActionPerformed(evt);
					}
				});

		jLabel6.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\User\\Desktop\\facultate\\TAIP\\PrivateStatisticsProject\\PrivateStatistics\\src\\interfaceModule\\java\\image3.jpg")); // NOI18N
		jLabel6.setMaximumSize(new java.awt.Dimension(1018, 360));

		jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
		jLabel5.setText("Name");

		jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
		jLabel7.setText("Age");

		jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
		jLabel8.setText("Cost");

		jButtonInsert.setText("INSERT");
		jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonInsertActionPerformed(evt);
			}
		});

		jButtonGenerateData.setText("Generate Data");
		jButtonGenerateData
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonGenerateDataActionPerformed(evt);
					}
				});
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(4, 4, 4)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel4)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jTextFieldQ,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		135,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						11,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jTextFieldP,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						133,
																						Short.MAX_VALUE)
																				.addComponent(
																						jTextFieldUserName))))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButtonSum,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		65,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jTextFieldSum))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(
																		jComboBoxUserLevel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		142,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(
																		layout.createSequentialGroup()
																				.addComponent(
																						jButtonCreate)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jButtonValidate))))
								.addGap(54, 54, 54))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(37, 37, 37)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel8)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		jTextFieldCost,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		87,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						jLabel7))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jTextFieldName,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						87,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jTextFieldAge,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										87,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										jButtonInsert)
																								.addComponent(
																										jButtonGenerateData)))))
								.addGap(119, 119, 119))
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(179,
																		179,
																		179)
																.addComponent(
																		jLabel1))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jSeparator1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		465,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jSeparator2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		465,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(50, 50,
																		50)
																.addComponent(
																		jLabel6,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		413,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(23, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addGap(30, 30,
																		30)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jTextFieldUserName,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel2))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jTextFieldP,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel3)))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jComboBoxUserLevel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButtonValidate)
																				.addComponent(
																						jButtonCreate))))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jButtonSum)
																.addComponent(
																		jTextFieldSum,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														jTextFieldQ,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(40, 40, 40)
								.addComponent(jSeparator1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										10,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel6,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(30, 30, 30)
								.addComponent(jSeparator2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jTextFieldName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel7)
												.addComponent(
														jTextFieldAge,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButtonInsert)
												.addComponent(
														jButtonGenerateData))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel8)
												.addComponent(
														jTextFieldCost,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(47, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// insert
	private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {
		String pStr = jTextFieldP.getText();
		String qStr = jTextFieldQ.getText();
		String userName = jTextFieldUserName.getText();
		String name = jTextFieldName.getText();
		String age = jTextFieldAge.getText();
		String cost = jTextFieldCost.getText();

		if (!ClientMethods.isNumeric(pStr)) {
			pStr = "0";
		}
		if (!ClientMethods.isNumeric(qStr)) {
			qStr = "0";
		}
		if (!ClientMethods.isNumeric(age)) {
			age = "0";
		}
		if (!ClientMethods.isNumeric(cost)) {
			cost = "0";
		}

		BigInteger p = new BigInteger(pStr);
		BigInteger q = new BigInteger(qStr);
		String userLevel = jComboBoxUserLevel.getSelectedItem().toString();
		UserLevelKeyLength keyLength = ClientMethods.GetUserLevel(userLevel);
		if (paillier == null) {
			paillier = ClientMethods.CreatePaillier(p, q, keyLength);
		}
		boolean result = ClientMethods.InsertData(paillier, userName,
				keyLength, name, new BigInteger(age), new BigInteger(cost));
		String msg = "";
		if (result) {
			msg = "Values inserted!";
		} else {
			msg = "Values were not inserted!";
		}
		JOptionPane.showMessageDialog(null, msg);
	}

	// generate data
	private void jButtonGenerateDataActionPerformed(
			java.awt.event.ActionEvent evt) {
		String pStr = jTextFieldP.getText();
		String qStr = jTextFieldQ.getText();
		String userName = jTextFieldUserName.getText();

		if (!ClientMethods.isNumeric(pStr)) {
			pStr = "0";
		}
		if (!ClientMethods.isNumeric(qStr)) {
			qStr = "0";
		}

		BigInteger p = new BigInteger(pStr);
		BigInteger q = new BigInteger(qStr);
		String userLevel = jComboBoxUserLevel.getSelectedItem().toString();
		UserLevelKeyLength keyLength = ClientMethods.GetUserLevel(userLevel);
		if (paillier == null) {
			paillier = ClientMethods.CreatePaillier(p, q, keyLength);
		}
		Random r = new Random();
		for (int i = 0; i < 10; i++) {

			int randAge = r.nextInt(1000);
			BigInteger age = new BigInteger(String.valueOf(randAge));
			String name = "username_" + randAge;
			int randCost = r.nextInt(10000);
			BigInteger cost = new BigInteger(String.valueOf(randCost));	
			boolean result = ClientMethods.InsertData(paillier, userName,
					keyLength, name, age, cost);
		}
		String msg = "";
//		if (result) {
			msg = "Values inserted!";
//		} else {
//			msg = "Values were not inserted!";
//		}
		JOptionPane.showMessageDialog(null, msg);
	}

	// create
	private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {
		String pStr = jTextFieldP.getText();
		String qStr = jTextFieldQ.getText();
		String userName = jTextFieldUserName.getText();

		if (!ClientMethods.isNumeric(pStr)) {
			pStr = "0";
		}
		if (!ClientMethods.isNumeric(qStr)) {
			qStr = "0";
		}

		BigInteger p = new BigInteger(pStr);
		BigInteger q = new BigInteger(qStr);
		String userLevel = jComboBoxUserLevel.getSelectedItem().toString();
		UserLevelKeyLength keyLength = ClientMethods.GetUserLevel(userLevel);

		if (paillier == null) {
			paillier = ClientMethods.CreatePaillier(p, q, keyLength);
		}

		ClientUser cl = ClientMethods.CreateUser(userName, keyLength);
		String msg;
		if (cl.getP() == null) {
			msg = String.format(
					"The username '%s' already exists in the database!",
					cl.getUsername());
		} else {
			msg = String
					.format("The username '%s' has been created as a '%s'! \n The P: %s ,\n Q: %s",
							cl.getUsername(), cl.getUserType().toString(), cl
									.getP().toString(), cl.getQ().toString());
		}
		JTextArea textarea = new JTextArea(msg);
		textarea.setEditable(true);
		JOptionPane.showMessageDialog(null, textarea);
	}

	// validate
	private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {
		String pStr = jTextFieldP.getText();
		String qStr = jTextFieldQ.getText();
		String userName = jTextFieldUserName.getText();
		if (!ClientMethods.isNumeric(pStr)) {
			pStr = "0";
		}
		if (!ClientMethods.isNumeric(qStr)) {
			qStr = "0";
		}

		BigInteger p = new BigInteger(pStr);
		BigInteger q = new BigInteger(qStr);
		String userLevel = jComboBoxUserLevel.getSelectedItem().toString();
		UserLevelKeyLength keyLength = ClientMethods.GetUserLevel(userLevel);

		if (paillier == null) {
			paillier = ClientMethods.CreatePaillier(p, q, keyLength);
		}
		Boolean valid;
		try {
			valid = ClientMethods.ValidateUsername(userName, paillier);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			valid = false;
		}
		String msg = "";
		if (valid) {
			msg = "The user's P and Q are valid!";
		} else {
			msg = "The user's P and Q are not valid!";
		}
		JOptionPane.showMessageDialog(null, msg);
	}

	// sum
	private void jButtonSumActionPerformed(java.awt.event.ActionEvent evt) {
		String pStr = jTextFieldP.getText();
		String qStr = jTextFieldQ.getText();
		String userName = jTextFieldUserName.getText();
		if (!ClientMethods.isNumeric(pStr)) {
			pStr = "0";
		}
		if (!ClientMethods.isNumeric(qStr)) {
			qStr = "0";
		}

		BigInteger p = new BigInteger(pStr);
		BigInteger q = new BigInteger(qStr);
		String userLevel = jComboBoxUserLevel.getSelectedItem().toString();
		UserLevelKeyLength keyLength = ClientMethods.GetUserLevel(userLevel);
		if (paillier == null) {
			paillier = ClientMethods.CreatePaillier(p, q, keyLength);
		}
		List<BigInteger> list = ClientMethods.GetUserList(userName);
		BigInteger sum = ClientMethods.Sum(list, paillier);
		BigInteger sumDecrypted = ClientMethods.Decrypt(sum, paillier);
		jTextFieldSum.setText(sumDecrypted.toString());
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButtonCreate;
	private javax.swing.JButton jButtonValidate;
	private javax.swing.JButton jButtonSum;
	private javax.swing.JButton jButtonInsert;
	private javax.swing.JButton jButtonGenerateData;
	private javax.swing.JComboBox jComboBoxUserLevel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTextField jTextFieldQ;
	private javax.swing.JTextField jTextFieldUserName;
	private javax.swing.JTextField jTextFieldP;
	private javax.swing.JTextField jTextFieldSum;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextFieldName;
	private javax.swing.JTextField jTextFieldAge;
	private javax.swing.JTextField jTextFieldCost;
	// End of variables declaration

	private Paillier paillier;
}
